import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import {AppContextProvider} from "./components/context";
// import {createContext, useEffect, useState} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const AuthContext = createContext<boolean>(false);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [isSessionActive, setIsSessionActive] = useState<boolean>(false);
  // useEffect(() => {
  //   function updateAuthState() {
  //     if (typeof window !== "undefined") {
  //       setIsSessionActive(localStorage.getItem("jwtToken") ? true : false);
  //     }
  //   }
  //   updateAuthState();
  //   window.addEventListener("authstate", updateAuthState);
  //   return () => {
  //     window.removeEventListener("authstate", updateAuthState);
  //   };
  // }, []);

  return (
    <html lang="pl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>
          <Navbar></Navbar>
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
